language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

notifications:
  email: false

before_install:
  - apt-get install cmake
  - apt-get install libgtest-dev

script:
  - mkdir build; pushd build;
  - "cmake .. && make && ctest ."
  - popd;
