language: cpp

sudo: false

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.8
      - g++-4.8

before_install:
  - "cd /home/travis/build/ && pwd"
  - "wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz"
  - "tar -xvf release-1.7.0.tar.gz"
  - "cd googletest-release-1.7.0 && cmake . && cmake --build . && mkdir lib && mv *.a lib/ && cd -"

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - "ls"
  - "cmake . && make && ctest ."

notifications:
  email: false
