language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

notifications:
  email: false

before_install:
  - source ./install-deps.sh

script:
  - ls -R
  - echo "CXX=${CXX}"
  - "cmake .. && make && ctest ."
